<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Page analyzer</title>
</head>
<body>
    <div class="col-lg-8 mx-auto p-4 py-md-5">
        <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
            <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                <span class="fs-4">Page analyzer</span>
            </a>
        </header>
        <main>
            <h1 class="text-body-emphasis">Checking the website for SEO suitability</h1>
            <p class="fs-5 col-md-8">Quickly and easily. Insert a website link to get started.</p>
            <div class="mb-5">
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="https://example.com" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </main>
        <footer class="pt-5 my-5 text-body-secondary border-top">
            <p>Created by <a href="https://github.com/BOMBYASCHER">Me</a> · © 2024</p>
        </footer>
    </div>
</body>
</html>